/* Overrides the Spirit stub in data.js. Loaded after data.js. */
(function () {
  if (!window.TQ2 || !window.TQ2.skills) return;
  window.TQ2.skills.spirit = {
    source: "Client screenshots 2026-09-25. Actives 3-3-3-1. Passives user-locked 2026-09-25 top\u2192bottom L\u2192R. Geometry 4-6-6-6-4 (26 names). Bottom-right 8-pointer = Nether Current.",
    layout: {
      actives: [
        ["Chthonic Pulse", "Reap", "Deathchill Aura"],
        ["Death Nova", "Deathward Beam", "Eidolon Guard"],
        ["Keres", "Athanekros", "Soul Vortex"],
        ["Dark Pact"]
      ],
      passives: [
        ["Bitter Malice", "Unliving Dominion", "Foul Miasma", "Ethereal Reach"],
        ["Unrelenting Horde", "Stolen Breath", "Toll of Passage", "Frozen Lament", "Ichor Surge", "Echoing Ward"],
        ["Undying Host", "Inevitability", "Finality", "Serenity", "Dark Arts", "Death's Door"],
        ["Otherworldly Army", "Ephemeral Rites", "Withering Touch", "Spirit Conduit", "Enervating Current", "Layered Veil"],
        ["Shadow Force", "Umbral Rites", "Artifacts of the Underworld", "Nether Current"]
      ]
    },
    actives: [
      { name: "Chthonic Pulse", type: "active", tags: "Main \u00b7 Spell \u00b7 Projectile \u00b7 Cold", cost: "44 Energy (Initial)", cd: "None", note: "32\u201348 Cold. Use 0.66s. 7% crit, 72% ailment. Slow-moving projectile. Projectile Penetration: Infinite. Target Penetration Effectiveness: 60%. Snapshot had Enhanced Ailments 4/5 and Cold Conversion 1/1.", mods: ["Vulnerable on Hit 1","Enhanced Damage 10","Enhanced Ailments 5","Mortality 3","Primed Kill Explosion 1","Long Shot 5","Doom on Hit 1","Soul Harvest 1","Health Cost 1","Returning Projectiles 1","Return Explosion 1","Trigger 1","Cold Conversion 1","Poison Conversion 1","Soulburn 1"] },
      { name: "Reap", type: "active", tags: "Main \u00b7 Spell \u00b7 Area", cost: "44 Energy (Initial)", cd: "None", note: "50\u201356 Damage. Cast 0.66s. 7% crit, 5% ailment. 100% Weapon Damage in a 120\u00b0 cone, 4m radius. 60% of Damage converted to Vitality. 10% Lifesteal.", mods: ["Vulnerable on Hit 1","Enhanced Damage 10","Enhanced Ailments 5","Enhanced Critical Hits 5","Execute 1","Mortality 3","Carnage on Kill 1","Doom on Hit 3","Consume Doom 3","Doom Explosion 2","Exhaust 1","Enhanced Area 5","Soul Harvest 1","Sacrifice 1","Health Cost 1","Weapon Attack 1"] },
      { name: "Deathchill Aura", type: "sustained", tags: "Aura \u00b7 Spell \u00b7 Vitality \u00b7 Area", cost: "22 Energy (Initial) + \u221244/s Energy (Recurring) + 44 Energy (Reserved)", cd: "None", note: "Instant. 16 Vitality. Emit aura 4m. 30% Chill chance in the aura every 0.5s. While active also deals 16 Vitality Damage in the aura every 0.5s.", mods: ["Health Reservation 1","Enhanced Area 5","Intensify 3","Weaken 5","Entropy 5","Focused Power 3","Execution Threshold 3","Spirit World 5"] },
      { name: "Death Nova", type: "active", tags: "Main \u00b7 Spell \u00b7 Area \u00b7 Vitality", cost: "No Cost", cd: "6s", note: "51 Vitality. Use 0.70s. 7% crit, 5% ailment. Ring of otherworldly energy expands over 1.5s in a 4.5m radius.", mods: ["Enhanced Damage 10","Mortality 3","Elemental Infusion 5","Doom on Hit 3","Enhanced Area 5","Cold Conversion 1","Poison Conversion 1","Soul Harvest 1","Sacrifice 1","Projectiles 2","Soulburn 1","Trigger 1","Athanekros Autonomy 1","Athanekros Command 1"] },
      { name: "Deathward Beam", type: "active", tags: "Main \u00b7 Spell \u00b7 Channel \u00b7 Vitality", cost: "44/s Energy (Recurring)", cd: "None", note: "63 DPS. Cast 0.30s. 1% ailment. Channel a beam dealing 54\u201372 Vitality Damage per second. Target Penetration 2. Target Penetration Effectiveness 30%. Does not scale with Cast Speed.", mods: ["Enhanced Damage 10","Enhanced Ailments 5","Mortality 3","Long Shot 5","Elemental Infusion 5","Cold Conversion 1","Poison Conversion 1","Soul Harvest 1","Apply Doom 3","Empowering Beam 1","Energy Siphon - Exhaust 1","Healing Beam 3","Penetration 3","Ramp Up 3","Soulburn 1"] },
      { name: "Eidolon Guard", type: "active", tags: "Lesser Summon \u00b7 Spell", cost: "66 Energy (Initial)", cd: "None", note: "Use 0.70s. Summon 1 Eidolon Guard. Limit 0. Health 400. Costs 1 Shade. Base Weapon Damage 17 Vitality. Attacks deal 50% of its Weapon Damage. 5% Health Decay/s; while alive gains 10% more Health Decay every 1s up to 200% more. On death, +60% Shade Generation.", mods: ["Strong Awakening 1","Detonation 1","Empowered Assault 3","Doom 3","Frenzied 1","Enhanced Damage 10","Squad Tactics 1","Life Link 1","Mass Summoning 2","Stable Manifestation 1","Unstable Frenzy 1","Charge 1","Essence Drain 1","Ether Strike 1"] },
      { name: "Keres", type: "sustained", tags: "Lesser Summon", cost: "55 Energy (Reserved)", cd: "None", note: "Instant. When you or your Summons kill an enemy, summon 1 Keres. Limit 0. Lifetime 15s. Intangible. Expends itself to debuff an enemy 10s: +23 Execution Threshold. One Keres debuff per enemy.", mods: ["Doom 3","Execution Threshold 3","Carnage 3","Weaken 3","Doom on Hit 3","Vitality Burst 3","Drink Essence 1","Rampage 1"] },
      { name: "Athanekros", type: "sustained", tags: "Greater Summon \u00b7 Spell", cost: "1 Maximum Shades (Reserved) + 60 Energy (Reserved)", cd: "4s", note: "Use 0.66s. Sustained: automatically summons and restores Athanekros. Active: Empower 5s and reduce Restoration Timer by 6s. Limit 0. Restoration 30s. Health 640. Base Weapon Damage 21 Vitality. Attacks deal 140% Weapon Damage. Empowered: 50% more Lifesteal.", mods: ["Autonomous Strength 1","Enhanced Damage 5","Enhanced Speed 3","Enhanced Health 3","Mental Link 3","Empowered Assault 3","Short Restoration 1","Energized 1","Doom 3","Weaken 3","Frenzied 1","Power Transfer 1","Arcane Blast 1","Soul Blight 1","Wraith Shell 1"] },
      { name: "Soul Vortex", type: "active", tags: "Spell \u00b7 Area \u00b7 Vitality \u00b7 Disruption", cost: "55 Energy (Initial)", cd: "9.1s", note: "68\u2013102 Total Damage. Cast 0.66s. 7% crit, 5% ailment. 14\u201320 Vitality in a 4m radius every 0.8s for 4s. Pull to center every 0.8s, Displacement Strength 150. Limit 1. Disruption skills share Cooldown.", mods: ["Enhanced Damage 10","Enhanced Ailments 5","Elemental Infusion 5","Enhanced Area 5","Soul Harvest 1","Sacrifice 1","Soulburn 1","Doom 3","Weaken 2","Gateway 1","Execution Threshold 3","Underworld Force 5","Intensify 5","Extended Duration 3"] },
      { name: "Dark Pact", type: "active", tags: "Buff \u00b7 Spell \u00b7 Blessing", cost: "4.8 Health (Initial) + \u221224/s Health (Recurring)", cd: "6s", note: "Instant. Buff 6s. 6% Current Health Cost per second. While active gains 20% increased Health Cost every 1s up to 100%. CD does not recover while active. Re-use deactivates early. Grants: 10% Total Damage, 30% Movement Speed, +20 Energy Regeneration.", mods: ["Enhanced Ailments 5","Enhanced Critical Hits 5","Vitality Retaliation 5","Unshackled 1","Mind Over Body 5","Unearthly Power 5","Soulburn 1","Razor's Edge 1","Gateway 1"] }
    ],
    passives: [
      { name: "Shadow Force", type: "passive", note: "Skill Damage + Summon Damage. L1: 3% Skill, summons +4% Damage. L2: 6% / +8%.", feats: "6/12 Damage on Summoning, Summon Damage, Damage per missing Shade, Summon Damage per missing Shade, Increasing Summon Damage" },
      { name: "Umbral Rites", type: "passive", note: "Soulburn skill Damage + Shade Generation Rate. L1: 5% Soulburn skill Damage, 3% Shade Gen. L2: 10% / 6%.", feats: "5/10 Maximum Shades, Combo, Shades for Energy Spent, Shades from Summon Death, Shade Generation, Critical Soulburn" },
      { name: "Artifacts of the Underworld", type: "passive", note: "Skill Damage + flat Skill Vitality. L1: 3% Skill, +0.2 Skill Vitality. L2: 6% / +0.4.", feats: "4/8 Lifesteal, Critical Hit Chance, Ailment Chance" },
      { name: "Nether Current", type: "passive", note: "Skill Damage + Energy Regeneration. Snapshot L8: 16% Skill, 24% Energy Regen. L9: 18% / 27%. This char MAX 8. Taken: 30% Skill Damage with skills that cost Energy, 10% increased Energy Cost, 10% Energy Regeneration.", feats: "Energy Regeneration, Increased Energy Regen, Skill Damage, Energy Gain" },
      { name: "Otherworldly Army", type: "passive", note: "Summon Damage + flat Summon Skill Vitality. L1: summons +4% Damage, +0 Skill Vitality. L2: +8% / +0 (flat 0 on this 0-mastery char).", feats: "6/12 Minion Master, Summon Critical Hit Chance, Summon Damage, Damage for Health, Lifesteal, Summon All Speed" },
      { name: "Ephemeral Rites", type: "passive", note: "Skill Damage, Cooldown Rate, Summon Damage, Summon CDR. L1: 2% Skill, 2% CDR, summons +2% Damage and +2% CDR. L2: 4% / 4% / +4% / +4%.", feats: "5/10 Cooldown Rate, Main Skills Cooldown Rate, Summon Cooldown Rate, Soulburn, Barrier Recovery, Energy Recovery, Cooldown Reduction, Summon Damage, Summon Death Cooldown" },
      { name: "Withering Touch", type: "passive", note: "Damage over Time + Ailment Chance. L1: 4% DoT, 4% Ailment Chance. L2: 8% / 8%.", feats: "6/12 Ailment Chance, Ailment Duration, Maximum Ailment Stacks, Damage over Time, Active Damage Over Time, Doomed Damage Over Time" },
      { name: "Spirit Conduit", type: "passive", note: "Elemental Damage, Infusion-skill Elemental, Elemental Ailment Damage. L1: 3% Ele, 2% Infusion Ele, 4% Ele Ailment Damage. L2: 6% / 4% / 8%.", feats: "6/12 Elemental Damage, Maximum Elemental Infusion, Shade Generation, Soulburn Infusion, Summon Elemental Damage" },
      { name: "Enervating Current", type: "passive", note: "Vitality Damage + Lifesteal. L1: 4% Vit, 6% Lifesteal. L2: 8% / 12%.", feats: "4/8 Ailment Exploit, Lifesteal, Stagger, Vitality Damage, Soulburn, Shared Damage - Vitality, Vitality Conversion" },
      { name: "Layered Veil", type: "passive", note: "Maximum Barrier + Barrier Conversion Rate. L1: 7% Max Barrier, 10% Conversion. L2: 14% / 20%.", feats: "6/12 Life Barrier, Burst Barrier, Shade Consume, Summon Damage, Barrier Regeneration, Barrier Decay Threshold" },
      { name: "Undying Host", type: "passive", note: "Summon Health, Summon Vitality Res, Summon Glancing. L1: +6% Health, +4% Vit Res, +1% Glancing. L2: +12% / +8% / +2%.", feats: "6/12 Vitality Resistance, Summon Health, Summon Speed, Summon Cooldown Rate" },
      { name: "Inevitability", type: "passive", note: "Execution Threshold. L1: +2. L2 tooltip also shows +2 (likely +2/level; confirm on a L2+ char).", feats: "6/12 Ailment - Mortality, Execution Against Incapacitated, Shade Regeneration, Mortality - Summons, Vulnerable Execution" },
      { name: "Finality", type: "passive", note: "Doom Damage + Doom Lifesteal. L1: 10% Doom Damage, 5% Doom Lifesteal. L2: 20% / 10%.", feats: "6/12 Maximum Doom, Rip & Tear, Ailment Exploit, Doom Explosion, Critical Hit Chance" },
      { name: "Serenity", type: "passive", note: "Maximum Energy + Free Energy Reservation. L1: 1% Max Energy, +4 Free Reservation. L2: 2% / +8.", feats: "6/12 Health to Energy, Energy Regeneration, Ether Shield, Free Energy Reservation, Maximum Energy" },
      { name: "Dark Arts", type: "passive", note: "Flat Spell Vitality (0 on this char), Spell Damage, Spell Ailment Chance. L1: +0 Spell Vit, 4% Spell Damage, 2% Spell Ailment Chance. L2: +0 / 8% / 4%.", feats: "6/12 Spell Critical Hit Chance, Spell Ailment Chance, Cast Speed, Master Sorcerer, Spell Damage, Cooldown Rate" },
      { name: "Death's Door", type: "passive", note: "Low Health Damage for you and summons. L1: 5% Damage while you are on Low Health; summons +5% Damage while you are on Low Health. L2: 10% / +10%.", feats: "4/8 Increased Health, Reduced Self Damage, Low Health Threshold, Damage per Missing Health, Reduced Health Cost, Skill Damage, Health on Kill, Critical Hit Chance" },
      { name: "Unrelenting Horde", type: "passive", note: "Summon Damage + Summon All Speed. L1: +4% Damage, +1% All Speed. L2: +8% / +2%.", feats: "6/12 Increasing Summon Crit Damage, Summon Damage, Summon Speed, Summon Critical Hit Chance, Increasing Summon Crit Chance" },
      { name: "Stolen Breath", type: "passive", note: "Flat Phys/Vit lifesteal + % Lifesteal + Summon Lifesteal. L1: +0.5% Phys LS, +0.5% Vit LS, 10% Lifesteal, summons +10% LS. L2: +1% / +1% / 20% / +20%.", feats: "6/12 Health Reservation Lifesteal, Lifesteal, Low Health Lifesteal, Intense Lifesteal, Summon Lifesteal" },
      { name: "Toll of Passage", type: "passive", note: "Shade Generation Rate. L1: 8%. L2: 16%.", feats: "6/12 Maximum Shades, Shade Generation, Low Health Shade Regeneration, Shade Regeneration, Shade Consumption Damage" },
      { name: "Frozen Lament", type: "passive", note: "Cold Damage + Chill Power. L1: 4% Cold, 2% Chill Power. L2: 8% / 4%.", feats: "4/8 Cold Damage, Chill Power, Maximum Chilled, Shared Damage - Cold, Soulburn, Chill, Ailment Exploit, Cold Conversion" },
      { name: "Ichor Surge", type: "passive", note: "Poison Damage + Plague Damage. L1: 4% Poison, 4% Plague. L2: 8% / 8%.", feats: "4/8 Poison Damage, Plagued Damage, Maximum Plagued, Shared Damage - Poison, Soulburn, Plague, Ailment Exploit, Poison Conversion" },
      { name: "Echoing Ward", type: "passive", note: "Barrier Regeneration + Barrier Decay Threshold. L1: +2 Regen, +5 Decay Threshold. L2: +3 / +9.", feats: "5/10 Barrier For Health, Barrier Decay Threshold, Barrier Regeneration, Barrier Cooldown Rate, Summon Death Barrier" },
      { name: "Bitter Malice", type: "passive", note: "Skill Damage + Vit/Cold/Poison Pen. L1: 2% Skill, +0.3% Vit Pen, +0.3% Cold Pen, +0.3% Poison Pen. L2: 4% / +0.6% / +0.6% / +0.6%.", feats: "8/16 Vitality Penetration, Cold Penetration, Poison Penetration" },
      { name: "Unliving Dominion", type: "passive", note: "Summon Damage + Summon Crit Chance. L1: summons +3% Damage, +0.5% Crit. L2: +6% / +1%.", feats: "8/16 Minion Master, Summon Critical Hit Chance, Summon Defenses" },
      { name: "Foul Miasma", type: "passive", note: "Ailment Chance + Ailment Power. L1: 2% Chance, 1% Power. L2: 4% / 2%.", feats: "8/16 Ailment Damage, Ailment Duration, Ailment Chance" },
      { name: "Ethereal Reach", type: "passive", note: "Vitality Damage, Lifesteal, Vitality Pen. L1: 2% Vit, 2% Lifesteal, +0.8% Vit Pen. L2: 4% / 4% / +1.6%.", feats: "8/16 Vitality Penetration, Vitality Damage, Lifesteal" }
    ]
  };
})();
