/* Overrides the Forge stub in data.js. Loaded after data.js. */
(function () {
  if (!window.TQ2 || !window.TQ2.skills) return;
  window.TQ2.skills.forge = {
    source: "Client screenshots 2026-09-25 (full inspect pass). 11 actives + 18 passives. Layout is bottom→up L→R (tier I first). Actives 2-3-4-2: I Force Field | Tempered Arsenal. II Blade Trap | Forge Call | Minefield. III Chains | Sentry | Armor Eruption | Metal Welding. IV Ironclad | Automaton. Passives 2-5-4-3-4. Divine Cores resource. 0-point inspect on dual Storm+Forge board.",
    layout: {
      actives: [
        ["Force Field", "Tempered Arsenal"],
        ["Blade Trap", "Forge Call", "Minefield"],
        ["Chains", "Sentry", "Armor Eruption", "Metal Welding"],
        ["Ironclad", "Automaton"]
      ],
      passives: [
        ["Salvager", "Sturdy Armor"],
        ["Forged Legion", "Curio Collector", "Reinforced Weaponry", "Elemental Utilization", "Armor Spikes"],
        ["Fortified Construction", "Expert Blueprints", "Overwhelming Forces", "Hardened Bulwark"],
        ["Improved Devices", "Heat of the Forge", "Elemental Engraving"],
        ["Annealed Wrath", "Living Armament", "Caustic Fumes", "Iron Domain"]
      ]
    },
    actives: [
      { name: "Blade Trap", type: "active", tags: "Lesser Summon · Device", cost: "5 Divine Cores (Initial)", cd: "None", note: "Use 0.50s. Summon a trap with spinning blades. On Activation deals 18 Pierce in 1.5m. Auto-activates every 0.8s. Max Activations 6. Summon Limit 2. Destroyed when Activations are depleted.", mods: ["Enhanced Area","Strong Start","Masterwork","Enfeeble","Burnout","Final Burst","Double Activation","Summon Limit","Elemental Infusion","Enhanced Activations","Frail","Explosion","Synchronized Attack","Conservation"] },
      { name: "Forge Call", type: "active", tags: "Spell · Projectile", cost: "5 Divine Cores (Initial)", cd: "8s", note: "Instant. 12–20 Damage. 5% crit, 5% ailment. 3 metal orbs orbit you. Each orb deals 12–20 Strike on contact. 4 Projectile Penetration. 1.5m orbit range.", mods: ["Enhanced Damage","Enhanced Critical Hits","Weaken on Hit","Fire Explosion","Heavy Impact","Enhancing Orbs","Additional Projectiles","Enhanced Ailments","Elemental Infusion","Heat Up","Electric Induction","Cooldown Refresh","Enhanced Glancing","Projectile Penetration","Empowered Projectiles","Weaponized Orbs"] },
      { name: "Minefield", type: "active", tags: "Main · Spell · Device", cost: "30 Energy (Initial) + 3 Divine Cores (Initial)", cd: "5s", note: "48–60 Damage. Cast 0.70s. 5% crit, 5% ailment. Throw 10 mines. Activate after 0.3s. Last 8s. Explode on contact for 48–60 Strike in 1m. Consecutive explosions on the same target deal 40% less.", mods: ["Enhanced Damage","Elemental Infusion","Additional Mines","Remote Activation","Enhanced Ailments","Enhanced Area","Cooldown Charges"] },
      { name: "Chains", type: "active", tags: "Spell · Area", cost: "No Cost", cd: "10s", note: "38–53 Damage. Cast 0.50s. 5% crit, 5% ailment. Throw chains. 38–53 Pierce and pull enemies toward you. Hit enemies Stunned 0.4s. 8m radius, 45° angle. Also picks up Divine Cores and Gold in the area.", mods: ["Enhanced Damage","Long Shot","Cooldown Charge","Shaken on Hit","Whirling Chains","Divine Core Generation","Enhanced Ailments","Elemental Infusion","Sunder","Additional Chains","Free Chains"] },
      { name: "Sentry", type: "active", tags: "Lesser Summon · Device", cost: "5 Divine Cores (Initial)", cd: "None", note: "Use 0.50s. Turret fires bolts at the closest enemy. On Activation deals 25 Pierce. Auto-activates every 0.8s. Max Activations 8. Summon Limit 2. Destroyed when Activations are depleted.", mods: ["Summon Limit","Elemental Infusion","Enhanced Activations","Burnout","Final Burst","Double Activation","Recycling","Strong Start","Masterwork","Frail","Explosion","Synchronized Attack","Conservation"] },
      { name: "Armor Eruption", type: "active", tags: "Main · Area · Projectile", cost: "No Cost", cd: "6s", note: "43–61 Damage. Use 0.70s. 5% crit, 5% ailment. Armor explodes for 26–35 Strike in 3m. You shoot armor as metal shards in all directions dealing 17–26 Pierce each. Skill Damage scales with Armor.", mods: ["Vulnerable on Hit","Enhanced Ailments","Enhanced Area","Cooldown Refresh","Enhanced Damage","Elemental Infusion","Divine Core Collector","Returning Projectiles"] },
      { name: "Metal Welding", type: "active", tags: "Spell · Area · Channel", cost: "30 Energy (Initial) + 5 Divine Cores (Initial)", cd: "None", note: "Use 0.68s. Reaches Stages every 0.68s as you Channel. Gain 25% increased Base Weapon Damage per stage for 5s after channeling ends. First Weapon Attack after channel ends deals 30% more Damage per Stage reached. Charge Time scales with 20% of Attack and Cast Speed.", mods: ["Damage Protection","Channel Barrier","Armor Up","Extended Duration","Divine Cores On Hit","First Strike","Channel Heal","Extended Charge","Cooldown Refresh","Fast Channel","Enhanced Welding"] },
      { name: "Ironclad", type: "active", tags: "Blessing", cost: "2 Divine Cores (Recurring) + 2 Divine Cores (Initial)", cd: "None", note: "Use 0.15s. Toggle. 2 Divine Cores per second. +32 Armor, 20% increased Total Armor, +50% Disruption and Stun Resistance, 40% less Movement Speed. Movement Skill cancels Ironclad. Cooldown starts after deactivation.", mods: ["Bulwark Generation","Armor Shards","Retaliation Damage","Pierce Retaliation","Unstoppable","Armor Stacking"] },
      { name: "Automaton", type: "sustained", tags: "Sustained · Greater Summon · Spell · Device", cost: "3 Divine Cores (Initial) + 60 Energy (Reserved)", cd: "4s", note: "Use 0.65s. Sustained: auto-summon and restore Automaton. Active: Empower 5s, Restoration Timer −6s, heal this Summon 8% Health. Summon: Limit 0 on empty inspect, Restoration 30s, Health 800, Base Weapon 21 Strike. Attacks 140% of Weapon Damage. +50% Activation Speed while Empowered.", mods: ["Detonation","Enhanced Damage","Enhanced Health","Empowered Assault","Energized","Fire Attachment","Lightning Attachment","Autonomous Strength","Enhanced Speed","Pierce Retaliation","Short Restoration","Frenzied","Cold Attachment","Shield Attachment","Enhanced Heal","Elemental Infusion Charged"] },
      { name: "Force Field", type: "active", tags: "Spell · Area", cost: "No Cost", cd: "8s", note: "Cast 0.70s. Force field at target, 6m length. Limit 1. Affected enemies deal 10% less Damage and have 20% less Movement Speed.", mods: ["Reactivation","Projectile Glancing","Skill Enhancement","Enhanced Summon Damage","Armor Up","Enhanced Control Duration","Fragile"] },
      { name: "Tempered Arsenal", type: "sustained", tags: "Aura · Buff", cost: "40 Energy (Reserved)", cd: "None", note: "Instant. 18m aura: you and allies +13 Armor and 8% increased Base Weapon Damage.", mods: ["Enhanced Glancing Hits","Fire Resistance","Health Reservation","Strike Imbuement","Enhanced Armor","Pierce Retaliation","Conservation","Fire Imbuement","Pierce Imbuement","Device Double Activation"] }
    ],
    passives: [
      { name: "Salvager", type: "passive", note: "Divine Core on-gain buff + double-drop chance. L1: gaining Divine Cores grants you and Summons 3% increased Damage for 8s; enemies +2% chance to drop double Divine Cores. L2: 6% Damage / +4% double.", feats: "Double Divine Cores, Maximum Divine Cores, Summon Damage" },
      { name: "Sturdy Armor", type: "passive", note: "Health, Armor, Summon tank. L1: 1% Health, 1% Armor, summons +4% Health and +1% Armor. L2: 2% / 2% / +8% / +2%.", feats: "Armor, Summon Health, Health" },
      { name: "Forged Legion", type: "passive", note: "Summon Damage + All Speed. L1: summons +4% Damage, +1% All Speed. L2: +8% / +2%.", feats: "Summon Damage, Summon Critical Hit Chance, Minion Master" },
      { name: "Curio Collector", type: "passive", note: "Max Divine Cores, double drop, collection range. L1: +1 Max Divine Cores, enemies +2% double Divine Cores, 2% Collection Range. L2: +2 / +4% / 4%.", feats: "Maximum Divine Cores, Divine Core Generator, Divine Core Collection Range" },
      { name: "Reinforced Weaponry", type: "passive", note: "Physical, Bleed, Summon Physical. L1: 3% Physical, 5% Bleed Damage, summons +3% Physical. L2: 6% / 10% / +6%.", feats: "Physical Damage, Damage against Ailment, Ailment Power" },
      { name: "Elemental Utilization", type: "passive", note: "Elemental Damage, extra after Infusion. L1: 2% Elemental; 2% Elemental if you consumed Elemental Infusion in the last 5s. L2: 4% / 4%.", feats: "Elemental Damage, Elemental Infusion, Elemental Balance" },
      { name: "Armor Spikes", type: "passive", note: "Retaliation + Pierce Retaliation from Armor. L1: 5% Retaliation Damage, +1 Pierce Retaliation (scales with Armor). L2: 10% / +2.", feats: "Physical Retaliation, Retaliation Range, Thorns" },
      { name: "Fortified Construction", type: "passive", note: "Summon Health + Armor. L1: summons +10% Health, +2% Armor. L2: +20% / +4%.", feats: "Health and Armor, Shield, Health Regeneration" },
      { name: "Expert Blueprints", type: "passive", note: "Device speed and damage. L1: Devices +2% All Speed; Device Skills and Devices +4% Damage. L2: +4% / +8%.", feats: "Device Damage, Explosion, Activation Speed" },
      { name: "Overwhelming Forces", type: "passive", note: "Overwhelm spend buff. L1: consuming Overwhelm grants you and Summons 3% increased Damage for 5s. L2: 6%.", feats: "Damage, Bulwark, Device Activations" },
      { name: "Hardened Bulwark", type: "passive", note: "Bulwark Effect + flat Armor. L1: 4% Bulwark Effect, +6 Armor. L2: 8% / +12.", feats: "Spiked Bulwark, Minimum Bulwark, Maximum Bulwark" },
      { name: "Improved Devices", type: "passive", note: "Double Activation + Activations. L1: activatable Devices +1% Double Activation Chance and 3% increased Activations. L2: +2% / 6%.", feats: "Activations, Double Activation, Immunity" },
      { name: "Heat of the Forge", type: "passive", note: "Health + Fire/Cold Res for you and Summons. L1: 1% Health, +4% Fire Res, +4% Cold Res; summons +4% Fire and +4% Cold Res. L2: 2% / +8% / +8% / +8% / +8%.", feats: "Health, Fire and Cold, Fire Retaliation" },
      { name: "Elemental Engraving", type: "passive", note: "Elemental + Infusion/Overload skill damage. L1: 2% Elemental, 2% Damage with Infusion Skills, 2% Damage with Overload Skills. L2: 4% / 4% / 4%.", feats: "Elemental Damage, Energy, Tranquility" },
      { name: "Annealed Wrath", type: "passive", note: "Skill Damage + Elemental/Physical Pen. L1: 2% Skill, +0.3% Elemental Pen, +0.3% Physical Pen. L2: 4% / +0.6% / +0.6%.", feats: "Physical Penetration, Penetration, Elemental Penetration" },
      { name: "Living Armament", type: "passive", note: "Summon Damage + Crit. L1: summons +3% Damage, +0.5% Crit. L2: +6% / +1%.", feats: "Minion Master, Summon Critical Hit Chance, Summon Defenses" },
      { name: "Caustic Fumes", type: "passive", note: "Ailment Chance + Power. L1: 2% Ailment Chance, 1% Ailment Power. L2: 4% / 2%.", feats: "Ailment Damage, Ailment Duration, Ailment Chance" },
      { name: "Iron Domain", type: "passive", note: "Physical Damage + Physical Pen. L1: 2% Physical, +0.8% Physical Pen. L2: 4% / +1.6%.", feats: "Physical Penetration, Strike Damage, Pierce Damage" }
    ]
  };
})();
